export enum AUTH_STRATEGIES {
  DISCORD_OAUTH2 = 'DISCORD_AUTH_STRATEGY',
  JWT_ACCESS = 'JWT_ACCESS_AUTH_STRATEGY',
  JWT_REFRESH = 'JWT_REFRESH_AUTH_STRATEGY',
  DISCORD_PROFILE = 'DISCORD_PROFILE_AUTH_STRATEGY',
}
