export enum AUTH_STRATEGIES {
  JWT_ACCESS = 'JWT_ACCESS_AUTH_STRATEGY',
  JWT_REFRESH = 'JWT_REFRESH_AUTH_STRATEGY',
  DISCORD_PROFILE = 'DISCORD_PROFILE_AUTH_STRATEGY',
  VK_PROFILE = 'VK_PROFILE_AUTH_STRATEGY',
}
