export enum SERVICES {
  USER = 'USER_SERVICE',
  AUTH = 'AUTH_SERVICE',
  DISCORD_AUTH = 'AUTH_DISCORD_SERVICE',
  DISCORD_PROFILE = 'AUTH_DISCORD_PROFILE_SERVICE',
  DISCORD_API = 'DISCORD_API_SERVICE',
  DISCORD_API_CLIENT = 'DISCORD_API_CLIENT_SERVICE',
}
